{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openfire.fullname" . }}
  labels:
    {{- include "openfire.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openfire.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
