{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openfire.fullname" . }}-db
  labels:
    {{- include "openfire.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.user | quote }}
  password: {{ required "database.password must be provided or database.existingSecret set" .Values.database.password | quote }}
{{- end }}
