apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfire.fullname" . }}-headless
  labels:
    {{- include "openfire.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: c2s
      port: {{ .Values.service.ports.client }}
      targetPort: c2s
    - name: s2s
      port: {{ .Values.service.ports.server }}
      targetPort: s2s
  selector:
    app.kubernetes.io/name: {{ include "openfire.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
